openapi: 3.0.1
info:
  title: vesper api
  version: 0.0.3

components:
  schemas:
    Question:
      type: object
      properties:
        questionId:
          type: string
          example: '3333333333'
        title:
          type: string
        body:
          type: string
        createdBy:
          type: string

    QuestionList:
      allOf:
        - $ref: '#/components/schemas/Pager'
        - type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/Question'
    User:
      type: object
      properties:
        userId:
          type: string
          example: '3333333333333'
        name:
          type: string
          example: 'Ko1103'

    UserList:
      allOf:
        - $ref: '#/components/schemas/Pager'
        - type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/User'

    Pager:
      type: object
      properties:
        totalCount:
          type: number
          example: 2
        currentPage:
          type: number
          example: 1
