version: 2

phases:
  install:
    commands:
      - echo "Entered the install phase..."
      - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
  build:
    commands:
      - echo "Entered the build phase..."
  post_build:
    commands:
      - echo "Entered the post_build phase..."
