version: 0.2

phases:
  install:
    commands:
      - echo "Entered the install phase..."
      - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vesper --domain-owner 893536458831 --query authorizationToken --output text`
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - export __OAS_VERSION=`/usr/local/bin/yq e '.info.version' specs/api.yaml`
      - export __REGISTRY_URL=https://vesper-893536458831.d.codeartifact.ap-northeast-1.amazonaws.com/npm/vesper-api/
      - export __NAME='vesper-oas-api'
      - npm install
  build:
    commands:
      - echo "Entered the build phase..."
      - npm run gen:openapi-yaml
      - cp ./specs/base.package.json ./openapi-yaml/package.json
      - cd openapi-yaml
        ## Update name in package.json
      - cat ./package.json | jq --arg __NM $__NAME '.name = $__NM' > ./package.json.tmp
      - mv ./package.json.tmp ./package.json
        ## update version in package.json
      - cat ./specs/base.package.json | jq --arg VERSION $__OAS_VERSION '.version  = $VERSION' > ./package.json.tmp
      - mv ./package.json.tmp ./package.json
        ## update publish registry in package.json
      - cat package.json | jq --arg REGISTRY_URL $__REGISTRY_URL '.publishConfig.registry = $REGISTRY_URL' > ./package.json.tmp
      - mv ./package.json.tmp ./package.json
      - cat ./package.json

  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - aws codeartifact login --tool npm --repository vesper-api --domain vesper --domain-owner 893536458831
      - pwd
      - npm run publish --repository=$__REGISTRY_URL
