openapi: 3.0.1
info:
  title: vesper api
  version: 0.0.4

servers:
  - url: /v1

tags:
  - name: questions
    description: 質問関連API
  - name: answers
    description: 回答関連API
  - name: users
    description: ユーザ関連API
  - name: system
    description: システム関連API

paths:
  '/questions':
    get:
      summary: get questions list
      x-exegesis-controller: questions
      x-exegesis-operationId: list
      description: 質問一覧取得
      tags:
        - questions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components/common.yaml#/components/schemas/QuestionList'
    post:
      summary: create question
      x-exegesis-controller: questions
      x-exegesis-operationId: create
      description: 質問作成
      tags:
        - questions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/common.yaml#/components/schemas/Question'
      responses:
        200:
          description: OK

  '/questions/{questionId}':
    get:
      summary: get questions list
      x-exegesis-controller: questions
      x-exegesis-operationId: list
      description: 質問一覧取得
      tags:
        - questions
      parameters:
        - name: questionId
          in: path
          description: 質問ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components/common.yaml#/components/schemas/Question'

  '/answers':
    get:
      summary: get answers list
      x-exegesis-controller: answers
      x-exegesis-operationId: list
      description: 回答一覧取得
      tags:
        - answers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components/common.yaml#/components/schemas/AnswerList'
    post:
      summary: create answer
      x-exegesis-controller: answers
      x-exegesis-operationId: create
      description: 回答作成
      tags:
        - answers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/common.yaml#/components/schemas/Answer'
      responses:
        200:
          description: OK

  '/users':
    get:
      summary: get user list
      x-exegesis-controller: users
      x-exegesis-operationId: list
      description: ユーザ一ー覧取得
      tags:
        - users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components/common.yaml#/components/schemas/UserList'

  '/ping':
    get:
      summary: ping
      x-exegesis-operationId: ping
      x-exegesis-controller: ping
      description: 死活監視
      tags:
        - system
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  '/ping/deep':
    get:
      summary: deep
      x-exegesis-operationId: deep
      x-exegesis-controller: ping
      tags:
        - system
      description: 死活監視(dbまで確認)
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
